// ============================================================
// EMBERHOLD — game content definitions
// All numbers here are the balance sheet. Later-era costs assume
// the trial rewards (Blueprints, Scarcity stacks) are obtainable.
// ============================================================

const SAVE_KEY = 'emberhold_save_v1';

// --- time ---
const DAY_RATE = 2;        // days per real second
const DAYS_PER_SEASON = 50;
const DAYS_PER_YEAR = 200; // one year = 100 real seconds

// --- resources ---
const RESOURCES = [
  { id: 'food',      name: 'Food',      note: 'eaten by every villager, day and night' },
  { id: 'wood',      name: 'Wood',      note: 'the bones of the village' },
  { id: 'stone',     name: 'Stone',     note: 'quarried once stone-working is learned' },
  { id: 'copper',    name: 'Copper',    note: 'trace veins become useful once prospectors and metallurgists take notice' },
  { id: 'tools',     name: 'Tools',     note: 'crafted at the Workbench; sharpen every trade' },
  { id: 'knowledge', name: 'Knowledge', note: 'the one store with no ceiling; spent on research' },
  { id: 'currency',  name: 'Currency',  note: 'funds arriving from trade with neighboring tribes' },
  { id: 'iron',      name: 'Iron',      note: 'pried from the deep seams' },
  { id: 'coal',      name: 'Coal',      note: 'burns hotter than wood' },
  { id: 'steel',     name: 'Steel',     note: 'smelted from iron and coal in the Forge' },
  { id: 'machinery', name: 'Machinery', note: 'each unit in storage hums +0.2% to all production' },
  { id: 'power',     name: 'Power',     note: 'generated by plants and consumed by powered industry' },
  { id: 'goods',     name: 'Industrial Goods', note: 'made only by a powered Factory' },
  { id: 'aether',    name: 'Aether',    note: 'gathered by those who watch the sky' },
];

// --- eras ---
const ERAS = [
  { name: 'Age of Ember' },
  { name: 'Age of Stone' },
  { name: 'Age of Iron' },
  { name: 'Age of Steam' },
  { name: 'Age of Light' },
];
const ERA_GATE = { stoneWorking: 2, metallurgy: 3, machineryTech: 4, astronomy: 5 };

// --- storage: every store except knowledge has a ceiling.
// capacity = (base + per * buildingLevel) * (1 + 0.2 per Overflow completion)
const STORAGE = {
  food:      { base: 200, per: 400, bld: 'storehouse' },
  wood:      { base: 200, per: 400, bld: 'storehouse' },
  stone:     { base: 150, per: 350, bld: 'storehouse' },
  tools:     { base: 50,  per: 60,  bld: 'storehouse' },
  iron:      { base: 100, per: 250, bld: 'deepStore' },
  copper:    { base: 25,  per: 100, bld: 'deepStore' },
  coal:      { base: 100, per: 300, bld: 'deepStore' },
  steel:     { base: 50,  per: 100, bld: 'deepStore' },
  machinery: { base: 10,  per: 50,  bld: 'vault' },
  aether:    { base: 25,  per: 50,  bld: 'vault' },
};

// --- jobs (per assigned worker, per second) ---
const JOBS = {
  forager:     { name: 'Forager',      res: 'food',      base: 0.55, desc: 'roots, berries, small game',
                 unlock: () => true },
  woodcutter:  { name: 'Woodcutter',   res: 'wood',      base: 0.45, desc: 'fells and splits timber',
                 unlock: () => true },
  miner:       { name: 'Miner',        res: 'stone',     base: 0.28, desc: 'pulls stone from the quarry',
                 unlock: () => bld('quarry') > 0 },
  thinker:     { name: 'Thinker',      res: 'knowledge', base: 0.12, desc: 'argues, measures, writes it down',
                 unlock: () => bld('library') > 0 },
  banker:      { name: 'Banker',      res: 'currency',  base: 0.08, desc: 'keeps trade moving and funds arriving',
                 trade: true, unlock: () => tech('banking') && tradeAvailable() },
  diplomat:   { name: 'Diplomat',    res: 'currency',  base: 0, targeted: true,
                desc: 'improves relations with an assigned tribe',
                unlock: () => tech('diplomacy') },
  performer:  { name: 'Performer',   base: 0, targeted: true,
                desc: 'keeps spirits high with song, story, and spectacle',
                unlock: () => bld('amphitheatre') > 0 },
  explorer:   { name: 'Explorer',    base: 0, targeted: true,
                desc: 'walks the old roads and gathers Survey points for future migrations',
                unlock: () => perm('explorers') },
  guard:       { name: 'Guard',       res: 'food',      base: 0.14, upkeep: 0.20, winterproof: true,
                 desc: 'recruits automatically outside the population; hunts between watches; barracks set capacity',
                 unlock: () => tech('guards') && bld('barracks') > 0 },
  digger:      { name: 'Coal Digger',  res: 'coal',      base: 0.14, desc: 'black dust under black fingernails',
                 unlock: () => bld('coalSeam') > 0 },
  ironminer:   { name: 'Iron Miner',   res: 'iron',      base: 0.11, desc: 'chases red veins into the dark',
                 unlock: () => bld('deepMine') > 0 },
  copperminer: { name: 'Copper Digger', res: 'copper',   base: 0.08, desc: 'follows green stains through the shallows',
                 unlock: () => tech('copperProspecting') },
  astronomer:  { name: 'Astronomer',   res: 'aether',    base: 0.05, desc: 'listens to the sky at night',
                 unlock: () => bld('observatory') > 0 },
  tinkerer:    { name: 'Tinkerer',    res: 'tools',      base: 0.025, desc: 'steadily assembles tools from wood and stone',
                 inputs: { wood: 0.06, stone: 0.02 },
                 unlock: () => (perm('tinkerers') || trialActive('tinkering')) && bld('workbench') > 0 },
};
const FOOD_PER_POP = 0.12; // food/s eaten per villager

// --- buildings ---
const BUILDINGS = [
  { id: 'hut', name: 'Hut', max: 40, scale: 1.35,
    cost: { wood: 30 },
    effect: () => `+3 population cap${perm('twinSouls') ? ' (+2 Twin Souls)' : ''}`,
    desc: 'shelter raises children' },

  { id: 'storehouse', name: 'Storehouse', max: 20, scale: 2.1,
    cost: { wood: 80 },
    effect: () => `+400 food and wood, +350 stone, +60 tools capacity`,
    desc: 'a ceiling for every granary; raise it' },

  { id: 'foragerLodge', name: 'Forager Lodge', max: 5, scale: 1.7,
    cost: { wood: 45 },
    effect: () => '+10% food production', desc: 'drying racks and seed lore' },

  { id: 'lumberYard', name: 'Lumber Yard', max: 5, scale: 1.7,
    cost: { wood: 70, tools: 10 },
    effect: () => '+10% wood production',
    req: () => tech('craftsmanship'), desc: 'saws instead of axes' },

  { id: 'quarry', name: 'Quarry', max: 1, scale: 1,
    cost: { wood: 150 },
    effect: () => 'unlocks Stone and Miners',
    req: () => tech('stoneWorking'), desc: 'the earth can be asked for more' },

  { id: 'stoneWorks', name: 'Stone Works', max: 3, scale: 1.7,
    cost: { stone: 90, wood: 40 },
    effect: () => '+10% stone production',
    req: () => bld('quarry') > 0, desc: 'cut stone fits where rubble will not' },

  { id: 'workbench', name: 'Workbench', max: 1, scale: 1,
    cost: { wood: 120 },
    effect: () => 'unlocks crafting of Tools',
    req: () => tech('craftsmanship'), desc: 'good tools repay their cost a hundredfold' },

  { id: 'library', name: 'Library', max: 3, scale: 1.8,
    cost: { wood: 100 },
    effect: () => 'unlocks Thinkers; +10% knowledge production',
    desc: 'memory, written down so it survives' },

  { id: 'monument', name: 'Monument', max: 1, scale: 1,
    cost: { wood: 260, stone: 220, tools: 15, currency: 20 },
    effect: () => 'unlocks the Trials',
    req: () => era() >= 3, desc: 'a stone that dares the village to be better' },

  { id: 'barracks', name: 'Barracks', max: Infinity, scale: 1.8,
    cost: { wood: 180, stone: 120, tools: 10 },
    effect: () => `+2 Guard capacity (maximum ${bld('barracks') * 2 + 2})`,
    req: () => tech('guards'), desc: 'a roof, a watch bell, and somewhere to hang a spear' },

  { id: 'trainingYard', name: 'Training Yard', max: Infinity, scale: 1.8,
    cost: { wood: 220, stone: 160, tools: 20 },
    effect: () => '−10% time to recruit replacement Guards per level (compounding)',
    req: () => tech('trainingYard'), desc: 'drills turn recruits into a watchful line' },

  { id: 'hospital', name: 'Hospital', max: Infinity, scale: 1.8,
    cost: { wood: 150, stone: 100, tools: 10 },
    effect: () => '−10% Guard healing and population growth time per level (compounding)',
    req: () => tech('hospital'), desc: 'care for the wounded and a healthy start for new families' },

  { id: 'deepMine', name: 'Deep Mine', max: 1, scale: 1,
    cost: { stone: 260, tools: 30 },
    effect: () => 'unlocks Iron and Iron Miners',
    req: () => tech('deepMining'), desc: 'the deep rock holds iron' },

  { id: 'deepStore', name: 'Deep Store', max: 12, scale: 2.0,
    cost: { wood: 400, stone: 300, tools: 25 },
    effect: () => '+250 iron, +100 copper, +300 coal, +100 steel capacity',
    req: () => tech('deepMining'), desc: 'sealed shafts that keep ore dry and safe' },

  { id: 'coalSeam', name: 'Coal Seam', max: 1, scale: 1,
    cost: { stone: 320, wood: 160 },
    effect: () => 'unlocks Coal and Coal Diggers',
    req: () => tech('seamMining'), desc: 'stone that burns' },

  { id: 'forge', name: 'Forge', max: Infinity, scale: 1.8,
    cost: { stone: 380, iron: 90, tools: 25, currency: 40 },
    effect: () => `smelts ${fmt(0.04 * bld('forge'))} Steel/s; consumes ${fmt(0.6 * bld('forge'))} Iron/s and ${fmt(0.4 * bld('forge'))} Coal/s`,
    req: () => tech('metallurgy'), desc: 'iron and carbon, disciplined by fire' },

  { id: 'aqueduct', name: 'Aqueduct', max: 2, scale: 1.8,
    cost: { stone: 520, wood: 220, tools: 15 },
    effect: () => '+20% food production, +4 population cap',
    req: () => tech('hydraulics'), desc: 'clean water, fat fields' },

  { id: 'shrine', name: 'Shrine', max: 5, scale: 1.8,
    cost: { wood: 220, stone: 220, currency: 30 },
    effect: () => '+5% all production',
    req: () => era() >= 3, desc: 'for whatever watches over Emberhold' },

  { id: 'amphitheatre', name: 'Amphitheatre', max: 1, scale: 1,
    cost: { wood: 260, stone: 340, currency: 60 },
    effect: () => 'unlocks Performers, who raise morale over time',
    req: () => tech('civics'), desc: 'a stage where the people remember how to be glad' },

  { id: 'workshop', name: 'Workshop', max: 1, scale: 1,
    cost: { iron: 260, tools: 60, currency: 80 },
    effect: () => 'unlocks crafting of Machinery',
    req: () => tech('machineryTech'), desc: 'devices that make devices' },

  { id: 'steamPlant', name: 'Steam Plant', max: 3, scale: 1.8,
    cost: { steel: 60, coal: 100, tools: 25, currency: 50 },
    effect: () => '+1.2 Power/s, consumes 0.8 Coal/s',
    req: () => tech('metallurgy'), desc: 'boilers and turbines make a new kind of work possible' },

  { id: 'dynamo', name: 'Dynamo', max: 1, scale: 1,
    cost: { copper: 140, steel: 50, machinery: 25, tools: 60, currency: 120, goods: 25 },
    effect: () => '+15% all production',
    req: () => tech('electricalEngineering'), desc: 'copper coils turn motion into possibility' },

  { id: 'vault', name: 'Vault', max: 12, scale: 2.0,
    cost: { steel: 100, tools: 80, currency: 100, goods: 30 },
    effect: () => '+50 machinery and aether capacity',
    req: () => tech('machineryTech'), desc: 'a quiet room where delicate things wait' },

  { id: 'factory', name: 'Factory', max: 3, scale: 1.8,
    cost: { steel: 70, tools: 55, currency: 90 },
    effect: () => '+10% all production; selectable powered production in the Village',
    req: () => (trialActive('industrialization') || perm('factory')) && tech('metallurgy'), desc: 'the drumbeat of the new age' },

  { id: 'observatory', name: 'Observatory', max: 1, scale: 1,
    cost: { steel: 130, machinery: 20, tools: 60, currency: 150, goods: 60 },
    effect: () => 'unlocks Aether and Astronomers',
    req: () => tech('astronomy') && expDone('sunkenRuins'),
    desc: 'the ruins held a lens; the sky holds more' },

  { id: 'beacon', name: 'The Beacon', max: 1, scale: 1,
    cost: { steel: 650, machinery: 260, aether: 130, knowledge: 4000, currency: 300, goods: 200 },
    effect: () => 'a light that will outlive the village',
    req: () => tech('optics'), desc: 'the end of the chronicle, or its beginning' },
];

// --- research ---
const TECHS = [
  { id: 'aphrodisiac', name: 'Aphrodisiac', cost: 50,
    desc: 'Reduces population growth time by 25%. Stacks with Hospitals.' },
  { id: 'hospital', name: 'Hospital', cost: 150,
    desc: 'Unlocks Hospitals. Each level reduces Guard healing and population growth time by 10%, compounding.',
    req: () => tech('stoneWorking') && tech('craftsmanship') },
  { id: 'stoneWorking', name: 'Stone Working', cost: 15,
    desc: 'Unlocks the Quarry. Enters the Age of Stone.' },
  { id: 'currency', name: 'Currency', cost: 100,
    desc: 'Unlocks trade with neighboring tribes and the Currency resource.',
    req: () => tech('stoneWorking') },
  { id: 'guards', name: 'Guards', cost: 100,
    desc: 'Unlocks Barracks and automatically recruited Guards, separate from the population, who hunt while keeping watch.',
    req: () => tech('stoneWorking') },
  { id: 'trainingYard', name: 'Training Yard', cost: 250,
    desc: 'Unlocks Training Yards. Each level reduces the time to recruit replacement Guards by 10%, compounding without a cap.',
    req: () => tech('guards') },
  { id: 'leatherArmor', name: 'Leather Armor', cost: 180,
    desc: 'Guards gain protection against raids from hardened leather and hide.',
    req: () => tech('guards') },
  { id: 'copperProspecting', name: 'Copper Prospecting', cost: 120,
    desc: 'Increases trace Copper extraction and unlocks Copper Diggers.',
    req: () => tech('stoneWorking') },
  { id: 'craftsmanship', name: 'Craftsmanship', cost: 40,
    desc: 'Unlocks the Workbench (Tools) and Lumber Yards.' },
  { id: 'writing', name: 'Writing', cost: 80,
    desc: '+25% knowledge production. The chronicle begins.' },
  { id: 'masonry', name: 'Masonry', cost: 150,
    desc: 'Unlocks Stone Works.',
    req: () => tech('craftsmanship') },
  { id: 'hydraulics', name: 'Hydraulics', cost: 260,
    desc: 'Unlocks the Aqueduct.',
    req: () => tech('masonry') },
  { id: 'deepMining', name: 'Deep Mining', cost: 320,
    desc: 'Unlocks the Deep Mine (Iron).',
    req: () => tech('craftsmanship') },
  { id: 'seamMining', name: 'Seam Surveying', cost: 450,
    desc: 'Unlocks the Coal Seam.',
    req: () => tech('deepMining') },
  { id: 'metallurgy', name: 'Metallurgy', cost: 600,
    desc: 'Unlocks the Forge and Steel. Enters the Age of Iron.',
    req: () => tech('seamMining') },
  { id: 'weaponry', name: 'Weaponry', cost: 300,
    desc: 'Guards hunt 50% more food and gain strength against raids with better arms.',
    req: () => tech('guards') && tech('metallurgy') },
  { id: 'machineryTech', name: 'Mechanism', cost: 1000,
    desc: 'Unlocks the Workshop (Machinery). Enters the Age of Steam.',
    req: () => tech('metallurgy') },
  { id: 'banking', name: 'Banking', cost: 900,
    desc: 'Unlocks Bankers, who increase the rate at which trade funds arrive.',
    req: () => tech('metallurgy') && tech('currency') },
  { id: 'diplomacy', name: 'Diplomacy', cost: 800,
    desc: 'Unlocks Diplomats, who can be assigned to improve relations with contacted tribes. Requires the Age of Iron.',
    req: () => era() >= 3 && tech('currency') },
  { id: 'civics', name: 'Civic Law', cost: 650,
    desc: 'Unlocks the Civic Hall and lets the village choose a governing policy.',
    req: () => tech('writing') && era() >= 3 },
  { id: 'council', name: 'The Council', cost: 1100,
    desc: 'Unlocks a Governor and two Council seats whose talents shape each Emberhold.',
    req: () => tech('civics') && tech('diplomacy') },
  { id: 'festivals', name: 'Civic Festivals', cost: 1400,
    desc: 'Raises the maximum Morale by 15.',
    req: () => tech('civics') && bld('amphitheatre') > 0 },
  { id: 'civicHarmony', name: 'Civic Harmony', cost: 2600,
    desc: 'Raises the maximum Morale by another 20.',
    req: () => tech('festivals') && tech('astronomy') },
  { id: 'weaponEfficiency', name: 'Weapon Efficiency', cost: 1200,
    desc: 'Guards hunt 75% more food through disciplined use of weapons.',
    req: () => tech('weaponry') && tech('machineryTech') },
  { id: 'electricalEngineering', name: 'Electrical Engineering', cost: 1600,
    desc: 'Improves Copper extraction and unlocks the Dynamo.',
    req: () => tech('machineryTech') },
  { id: 'astronomy', name: 'Astronomy', cost: 1800,
    desc: 'Unlocks the Observatory — requires the Sunken Ruins expedition. Enters the Age of Light.',
    req: () => tech('machineryTech') },
  { id: 'optics', name: 'Optics', cost: 3000,
    desc: 'Unlocks the Beacon.',
    req: () => tech('astronomy') },
];

// --- civics and council: one policy plus a governor and two advisors per run ---
const CIVICS = [
  { id: 'commons', name: 'Common Granaries', mods: { food: 1.15 }, storage: 1.20,
    desc: '+15% food production, +20% storage ceilings.' },
  { id: 'charter', name: 'Merchant Charter', mods: { currency: 1.25 }, cost: 0.90,
    desc: '+25% Currency, −10% building costs.' },
  { id: 'guilds', name: 'Craft Guilds', mods: { tools: 1.20, steel: 1.15, goods: 1.15 },
    desc: '+20% Tools and +15% Steel and Industrial Goods.' },
  { id: 'academy', name: 'Open Academy', mods: { knowledge: 1.20, aether: 1.10 },
    desc: '+20% Knowledge and +10% Aether.' },
  { id: 'warCouncil', name: 'War Council', defense: 1.30, mods: { food: 0.95 },
    desc: '+30% raid strength; −5% food production.' },
];

const GOVERNORS = [
  { id: 'quartermaster', name: 'Maela, the Quartermaster', storage: 1.15,
    desc: '+15% storage ceilings.' },
  { id: 'marshal', name: 'Orren, the Marshal', defense: 1.25,
    desc: '+25% raid strength.' },
  { id: 'archivist', name: 'Sera, the Archivist', mods: { knowledge: 1.20 },
    desc: '+20% Knowledge.' },
];

const COUNCILORS = [
  { id: 'granaryKeeper', name: 'Tovin, Keeper of Granaries', mods: { food: 1.10 }, desc: '+10% food production.' },
  { id: 'builder', name: 'Nera, Master Builder', cost: 0.90, desc: '−10% building costs.' },
  { id: 'envoy', name: 'Ilyan, Trade Envoy', mods: { currency: 1.20 }, desc: '+20% Currency.' },
  { id: 'forgeSpeaker', name: 'Brakka, Forge Speaker', mods: { tools: 1.15, steel: 1.15, goods: 1.15 }, desc: '+15% Tools, Steel, and Industrial Goods.' },
  { id: 'fieldWarden', name: 'Vey, Field Warden', defense: 1.12, mods: { food: 1.05 }, desc: '+12% raid strength, +5% food production.' },
];

// --- unscheduled happenings: mostly troublesome, occasionally heartening ---
const RANDOM_EVENTS = [
  { text: 'A goose has claimed the council table. No one can explain how it got there.', delta: [1, 4] },
  { text: 'A traveling puppeteer performs for the children. The adults pretend not to enjoy it.', delta: [2, 6] },
  { text: 'A barrel of winter apples is found behind the old palisade.', delta: [2, 5], food: [10, 25] },
  { text: 'A rumor spreads that the moon is watching the village.', delta: [-2, -7] },
  { text: 'The communal stew turns sour before anyone notices.', delta: [-3, -9], food: [-15, -5] },
  { text: 'A cart axle breaks in the mud, delaying half the morning\'s work.', delta: [-2, -6] },
  { text: 'A child releases all the carefully penned chickens.', delta: [-1, -5] },
  { text: 'The night watch hears wolves beyond the fields.', delta: [-3, -10] },
  { text: 'A roof gives way under wet snow. The repairs will be embarrassing.', delta: [-4, -12], wood: [-30, -10] },
  { text: 'A visiting merchant cheats three villagers with a remarkably obvious shell game.', delta: [-2, -8], currency: [-8, -2] },
  { text: 'A song from the old country is remembered, verse by verse.', delta: [2, 7] },
  { text: 'Someone has painted a heroic portrait of the village dog.', delta: [1, 5] },
];

// Each lineage has a purely atmospheric scene and a small consequential event.
// Resource effects only apply to resources the settlement has discovered.
const LINEAGE_EVENTS = {
  human: [
    { text: 'An Emberborn child asks why every new village has the same name. Three elders offer four different answers.' },
    { text: 'Emberborn neighbors hold a mending day, rescuing useful timber from abandoned furniture.', wood: [8, 18] },
  ],
  stonekin: [
    { text: 'Two Stonekin spend the afternoon debating whether a pebble resembles an ancestor. The pebble declines to comment.' },
    { text: 'A Stonekin mason hears a promising note beneath the chisel and splits a clean block from the rubble.', stone: [8, 18] },
  ],
  marshfolk: [
    { text: 'Marshfolk children launch reed boats bearing solemn messages to frogs on the opposite bank.' },
    { text: 'Marshfolk gardeners uncover a forgotten bed of edible roots beneath the reeds.', food: [10, 22] },
  ],
  skyborn: [
    { text: 'A Skyborn elder names every cloud above the village. One is apparently an old rival.' },
    { text: 'Skyborn kite watchers compare their wind charts and settle a longstanding question.', knowledge: [5, 12] },
  ],
  mephit: [
    { text: 'The Mephits hold a perfume contest. The judges insist that everyone else is missing the subtle notes.' },
    { text: 'A Mephit scent brewer uncorks a festival blend too enthusiastically. The square empties in seconds.', delta: [-4, -2] },
  ],
  dunewalkers: [
    { text: 'Dunewalker storytellers arrange their cushions like a caravan and argue over who gets to play the stubborn camel.' },
    { text: 'A Dunewalker merchant spots an error in an old tally and returns the overpayment to the village.', currency: [3, 8] },
  ],
  cinderforged: [
    { text: 'Cinderforged smiths tap their supper bowls in the rhythm of a forging song. The cook demands a quieter encore.' },
    { text: 'A Cinderforged apprentice leaves the fuel hatch open through a long story. Some coal burns to ash.', coal: [-8, -3] },
  ],
  thornkin: [
    { text: 'A Thornkin doorway blooms overnight. Its residents politely ask visitors to knock on the other branch.' },
    { text: 'Thornkin pruners guide an overgrown arbor back into shape and share the straight fallen branches.', wood: [10, 20] },
  ],
  clocklings: [
    { text: 'Every Clockling alarm rings at once, except the official village clock, which appears deeply embarrassed.' },
    { text: 'Clockling tinkerers assemble several useful implements from a box labeled probably spare parts.', tools: [1, 3] },
  ],
  glimmerfolk: [
    { text: 'Glimmerfolk singers rehearse a lullaby for a crystal that refuses to stop glowing after bedtime.' },
    { text: 'A Glimmerfolk choir finds a clear new harmony that leaves the whole village quietly smiling.', delta: [2, 5] },
  ],
  otterfolk: [
    { text: 'Otterfolk float hand in hand through an evening storytelling circle. The youngest keeps drifting ahead to the ending.' },
    { text: 'An Otterfolk diving crew follows a silver shoal into the shallows and returns with a shared catch.', food: [10, 22] },
  ],
  beaverkin: [
    { text: 'A Beaverkin inspector declares a decorative footbridge structurally excellent but insufficiently chewy.' },
    { text: 'Beaverkin builders dismantle an obsolete spillway and recover its seasoned beams.', wood: [12, 24] },
  ],
  turtlefolk: [
    { text: 'The Turtlefolk annual walking race reaches its first bend. Spectators settle in for a pleasant afternoon.' },
    { text: 'A Turtlefolk elder traces a lake memory on a slate, completing a map begun generations ago.', knowledge: [5, 12] },
  ],
  axolotlkin: [
    { text: 'Axolotlkin students practice looking solemn during a submerged lecture. Their waving gills betray their laughter.' },
    { text: 'Axolotlkin pond keepers observe an unfamiliar glow and carefully record its changing rhythm.', knowledge: [6, 14] },
  ],
  carpfolk: [
    { text: 'Carpfolk decorate the underwater lanes with smooth stones, then politely debate which direction counts as upstreet.' },
    { text: 'A silt cloud settles over a Carpfolk growing terrace, spoiling part of the gathered water greens.', food: [-12, -5] },
  ],
  frogfolk: [
    { text: 'A Frogfolk evening chorus pauses while one singer retrieves a particularly interesting moth.' },
    { text: 'Frogfolk singers answer the first warm rain with a chorus that draws smiles from every doorway.', delta: [2, 5] },
  ],
  heronkin: [
    { text: 'A Heronkin fishing teacher demonstrates perfect stillness. The pupils wonder whether class has actually started.' },
    { text: 'Heronkin fishers spot a crowded backwater and bring home enough to share beyond their stilt houses.', food: [8, 20] },
  ],
  foxfolk: [
    { text: 'A Foxfolk storyteller sells the same joke with three different endings. All three audiences insist theirs was the original.' },
    { text: 'A Foxfolk trader negotiates a small rebate by remembering exactly what was promised last spring.', currency: [3, 8] },
  ],
  wolfkin: [
    { text: 'Wolfkin pups rehearse a moon greeting. An elder gently explains that volume is only half the tradition.' },
    { text: 'A Wolfkin hunting pack returns early and lays an unexpected catch before the communal hearth.', food: [10, 22] },
  ],
  bearfolk: [
    { text: 'A Bearfolk carpenter falls asleep testing a new chair. The workshop accepts this as a favorable review.' },
    { text: 'Bearfolk gatherers discover a honey tree and insist on sharing before anyone starts counting portions.', food: [8, 16], delta: [1, 3] },
  ],
  deerkin: [
    { text: 'Deerkin dancers weave ribbons between their antlers for a procession that requires very careful doorways.' },
    { text: 'A Deerkin orchard walk finds an overlooked stand of ripe fruit at the edge of the commons.', food: [10, 20] },
  ],
  rabbitfolk: [
    { text: 'Rabbitfolk children give every warren junction a new name. The adults request a map before supper.' },
    { text: 'A Rabbitfolk seed store proves damp behind the lowest shelves. A few provisions must be discarded.', food: [-10, -4] },
  ],
  bisonkin: [
    { text: 'Bisonkin elders braid bright threads into their winter coats, each knot recalling a different journey.' },
    { text: 'Bisonkin families gather for a low humming song that can be felt through the floor of the great house.', delta: [2, 5] },
  ],
  squirrelfolk: [
    { text: 'A Squirrelfolk archivist files a nut under important historical objects and refuses to explain further.' },
    { text: 'A Squirrelfolk child remembers a forgotten cache while telling an unrelated story. Supper improves immediately.', food: [8, 18] },
  ],
  owlkin: [
    { text: 'An Owlkin reading circle observes a respectful silence so complete that nobody notices the meeting has ended.' },
    { text: 'Owlkin observers compare marginal notes and resolve a puzzle that had kept several scholars awake.', knowledge: [6, 14] },
  ],
  lynxfolk: [
    { text: 'A Lynxfolk tracker reconstructs an elaborate mystery from footprints. The culprit was carrying the laundry.' },
    { text: 'Lynxfolk scouts follow green stains along a ledge and collect a handful of loose copper nodules.', copper: [2, 5] },
  ],
  ibexkin: [
    { text: 'Ibexkin youngsters choose the least convenient ledge for a picnic and rate the view unanimously excellent.' },
    { text: 'An Ibexkin hauling team clears a cliff path and brings the sound stone back to the builders.', stone: [10, 22] },
  ],
  eaglefolk: [
    { text: 'An Eaglefolk messenger circles the aerie twice to finish a particularly satisfying story before landing.' },
    { text: 'Eaglefolk sky watchers sketch a rare pattern of high clouds before the mountain wind scatters it.', knowledge: [5, 12] },
  ],
  molekin: [
    { text: 'Molekin neighbors exchange tapping greetings through their walls. One household requests slower gossip.' },
    { text: 'Molekin tunnelers shore up a slumping side passage, using a few beams from the village store.', wood: [-10, -4] },
  ],
  raccoonfolk: [
    { text: 'A Raccoonfolk collector unveils a magnificent display of shiny objects, none of which anyone can identify.' },
    { text: 'Raccoonfolk salvagers restore a box of bent implements with patient fingers and questionable confidence.', tools: [1, 3] },
  ],
};

// Shared factory production line; rates and inputs are per factory per second.
const FACTORY_RECIPES = [
  { id: 'goods', name: 'Industrial Goods', rate: 0.08, inputs: {}, tech: null, unlock: 'Always available' },
  { id: 'tools', name: 'Tools', rate: 0.08, inputs: { wood: 3.2 }, tech: 'craftsmanship', unlock: 'Craftsmanship' },
  { id: 'steel', name: 'Steel', rate: 0.04, inputs: { iron: 0.6, coal: 0.4 }, tech: 'metallurgy', unlock: 'Metallurgy' },
  { id: 'machinery', name: 'Machinery', rate: 0.02, inputs: { steel: 0.1, coal: 0.4 }, tech: 'machineryTech', unlock: 'Mechanism' },
];

// --- crafting (instant conversions) ---
const CRAFTS = [
  { id: 'tools',     name: 'Tools',     give: { tools: 1 },     cost: { wood: 40 },
    req: () => bld('workbench') > 0, desc: 'carved and fire-hardened' },
  { id: 'machinery', name: 'Machinery', give: { machinery: 1 }, cost: { steel: 5, coal: 20 },
    req: () => bld('workshop') > 0, desc: 'gears, springs, patience' },
];

// --- trials: challenge modes. repeat = 0 means once-only. ---
const TRIALS = [
  { id: 'scarcity', name: 'Trial of Scarcity', repeat: 5,
    mod: 'Food production is halved.',
    goal: 'Keep the village fed for 240 days. If the food ever runs out, the trial fails.',
    reward: '+10% food production, permanently, for each completion.' },

  { id: 'frugality', name: 'Trial of Frugality', repeat: 3,
    mod: 'All building costs are raised by 50%.',
    goal: 'Complete 12 constructions while the trial is active.',
    reward: 'All building costs reduced 10%, permanently, for each completion.' },

  { id: 'overflow', name: 'Trial of the Overflow', repeat: 3,
    mod: 'No new storage may be built while the oath stands.',
    goal: 'Have every store you have discovered filled to its ceiling at the same moment.',
    reward: 'All storage ceilings +20%, permanently, for each completion.',
    req: () => bld('storehouse') > 0 },

  { id: 'tinkering', name: 'Trial of Tinkering', repeat: 0,
    mod: 'Tools may not be crafted by hand while the oath stands.',
    goal: 'Assign at least one Tinkerer and keep the Workbench running for 240 days without manually crafting Tools.',
    reward: 'Tinkerers: unlocks a job that steadily assembles Tools from wood and stone.',
    req: () => bld('workbench') > 0 },

  { id: 'wayfinding', name: 'Trial of Wayfinding', repeat: 0,
    mod: 'The village must spend time and supplies to learn the roads beyond its hearth.',
    goal: 'Complete the Old Forest expedition while the oath stands.',
    reward: 'Explorers: unlocks a worker who slowly earns Survey points for future migrations.',
    req: () => era() >= 2 && bld('quarry') > 0 },

  { id: 'silence', name: 'Trial of Silence', repeat: 0,
    mod: 'Knowledge production is stopped entirely.',
    goal: 'Produce 100 Steel after researching Metallurgy, spending only what was hoarded before the silence.',
    reward: 'Oral Tradition: Thinkers produce +50% knowledge, permanently.',
    req: () => era() >= 2 },

  { id: 'longnight', name: 'Trial of the Long Night', repeat: 0,
    mod: 'Winters are brutally harsh: food production x0.25 during winter.',
    goal: 'Survive a full year under the trial (200 days).',
    reward: 'Everwarm: winter food penalty halved (x0.75) and +5% to all production, permanently.' },

  { id: 'solitude', name: 'Trial of Solitude', repeat: 0,
    mod: 'The village is capped at 10 villagers. No children are born past ten.',
    goal: 'Stockpile 800 knowledge with only ten minds.',
    reward: 'Twin Souls: every Hut grants +2 extra population cap, permanently.' },

  { id: 'haste', name: 'Trial of Haste', repeat: 0,
    mod: 'All production reduced by 30%.',
    goal: 'Reach the Age of Light within 1200 days of starting the trial.',
    reward: 'Blueprints: all building costs reduced 15%, permanently.',
    req: () => era() >= 3 },

  { id: 'industrialization', name: 'Trial of Industrialization', repeat: 0,
    mod: 'Factories require a steady supply of Power to produce Industrial Goods.',
    goal: 'Build a Factory and produce 100 Industrial Goods within 1200 days.',
    reward: 'Industrialization: Factories remain available in every future Emberhold.',
    req: () => tech('metallurgy') && bld('coalSeam') > 0 && state.res.coal > 0 },
  { id: 'expansion', name: 'Trial of Expansion', repeat: 0,
    mod: 'The village must prove it can grow without wasting a foundation.',
    goal: 'Complete 8 constructions while the trial is active.',
    reward: 'Master Builders: unlocks one additional construction queue slot, permanently.',
    req: () => bld('monument') > 0 },
  { id: 'scholarship', name: 'Trial of Scholarship', repeat: 0,
    mod: 'The village must invest its knowledge before it can claim another voice in the archive.',
    goal: 'Complete 5 research projects while the trial is active.',
    reward: 'Grand Archive: unlocks one additional research queue slot, permanently.',
    req: () => bld('monument') > 0 },
];

// --- landings: where the migration ends up. Modifiers multiply production
// of that resource (passive income included). The road decides, for now.
const LANDINGS = [
  { id: 'emberplain', name: 'The Emberplain', habitats: ['plains'], mods: {},
    text: 'A wide plain of ash-grass and old roads. Nothing comes easy; nothing is denied.' },
  { id: 'greenfold', name: 'The Greenfold', habitats: ['forest'], mods: { wood: 1.25, stone: 0.8, iron: 0.8 },
    text: 'Old oak country. Timber for the taking — but the ground hoards its stone and iron.' },
  { id: 'grayrocks', name: 'The Grayrocks', habitats: ['mountain'], mods: { stone: 1.3, iron: 1.25, food: 0.8 },
    text: 'High, thin-soiled country. Stone and ore in abundance; the fields are poor.' },
  { id: 'floodmeadows', name: 'The Floodmeadows', habitats: ['water', 'wetland', 'plains'], mods: { food: 1.25, wood: 0.85 },
    text: 'A river\'s patience made this ground rich. Trees are few and far between.' },
  { id: 'ashfen', name: 'The Ashfen', habitats: ['wetland'], mods: { coal: 1.35, food: 0.85 },
    text: 'The ground smokes gently here. Coal for the digging, but little cares to grow.' },
  { id: 'windmere', name: 'The Windmere', habitats: ['water', 'wetland'], mods: { knowledge: 1.2, aether: 1.15, food: 0.9 },
    text: 'Still water under open sky. Minds are clear here; bellies less so.' },
];

// Habitat lists match any listed habitat; omitted lists allow every landing.
// Shared definitions keep animal neighbors and inherited lineages in sync.
const ANIMAL_LINEAGES = [
  { id: 'otterfolk', name: 'Otterfolk', habitats: ['water'], mods: { food: 1.22, currency: 1.15, iron: 0.90 },
    desc: 'Otter raft families fish the deep channels and ferry goods between floating markets.' },
  { id: 'beaverkin', name: 'Beaverkin', habitats: ['water'], mods: { wood: 1.25, tools: 1.15, aether: 0.88 },
    desc: 'Beaver engineers raise timber lodges and waterworks along broad rivers and lakes.' },
  { id: 'turtlefolk', name: 'Turtlefolk', habitats: ['water'], mods: { food: 1.18, knowledge: 1.20, machinery: 0.88 },
    desc: 'Freshwater turtle elders tend floating gardens and preserve generations of careful observations.' },
  { id: 'axolotlkin', name: 'Axolotlkin', habitats: ['water'], mods: { knowledge: 1.25, aether: 1.15, coal: 0.85 },
    desc: 'Feathery-gilled lake dwellers study luminous pools from submerged libraries.' },
  { id: 'carpfolk', name: 'Carpfolk', habitats: ['water'], mods: { food: 1.30, currency: 1.10, tools: 0.88 },
    desc: 'Carp communities cultivate underwater terraces and exchange harvests at shore markets.' },
  { id: 'frogfolk', name: 'Frogfolk', habitats: ['wetland'], mods: { food: 1.20, aether: 1.20, steel: 0.88 },
    desc: 'Frog reed singers cultivate marsh insects and read the weather in ripples and chorus.' },
  { id: 'heronkin', name: 'Heronkin', habitats: ['wetland'], mods: { knowledge: 1.22, food: 1.12, wood: 0.90 },
    desc: 'Heron stilt villages practice patient fishing and chart the changing wetland seasons.' },
  { id: 'foxfolk', name: 'Foxfolk', mods: { currency: 1.25, knowledge: 1.12, stone: 0.90 },
    desc: 'Fox traveling merchants adapt to any country, collecting stories and negotiating clever bargains.' },
  { id: 'wolfkin', name: 'Wolfkin', mods: { food: 1.22, tools: 1.12, currency: 0.90 },
    desc: 'Wolf packs share the hunt and maintain dependable tools, valuing communal stores above coin.' },
  { id: 'bearfolk', name: 'Bearfolk', habitats: ['forest', 'mountain'], mods: { wood: 1.20, stone: 1.20, currency: 0.88 },
    desc: 'Bear clans build stout woodland and mountain homes, hauling heavy materials with ease.' },
  { id: 'deerkin', name: 'Deerkin', habitats: ['forest', 'plains'], mods: { food: 1.20, wood: 1.15, iron: 0.88 },
    desc: 'Deer orchard keepers follow the edges of woodland and meadow, tending broad green commons.' },
  { id: 'rabbitfolk', name: 'Rabbitfolk', habitats: ['plains'], mods: { food: 1.28, goods: 1.10, coal: 0.85 },
    desc: 'Rabbit warrens spread beneath open fields, linking productive gardens with busy cottage workshops.' },
  { id: 'bisonkin', name: 'Bisonkin', habitats: ['plains'], mods: { food: 1.15, goods: 1.25, aether: 0.88 },
    desc: 'Bison herds settle the grasslands in great communal houses supplied by mills and grazing fields.' },
  { id: 'squirrelfolk', name: 'Squirrelfolk', habitats: ['forest'], mods: { wood: 1.28, tools: 1.15, steel: 0.85 },
    desc: 'Squirrel canopy towns connect timber workshops with ropeways and carefully stocked nut stores.' },
  { id: 'owlkin', name: 'Owlkin', habitats: ['forest'], mods: { knowledge: 1.28, aether: 1.12, goods: 0.88 },
    desc: 'Owl scholars keep quiet observatories in old trees, recording the night beneath living roofs.' },
  { id: 'lynxfolk', name: 'Lynxfolk', habitats: ['forest', 'mountain'], mods: { food: 1.18, copper: 1.22, currency: 0.88 },
    desc: 'Lynx trackers explore wooded slopes, finding game trails and overlooked copper seams.' },
  { id: 'ibexkin', name: 'Ibexkin', habitats: ['mountain'], mods: { stone: 1.25, iron: 1.18, wood: 0.88 },
    desc: 'Ibex cliff builders carry stone and ore along paths too steep for ordinary caravans.' },
  { id: 'eaglefolk', name: 'Eaglefolk', habitats: ['mountain'], mods: { aether: 1.25, knowledge: 1.18, food: 0.88 },
    desc: 'Eagle aerie watchers survey the high peaks and harvest insights from clear mountain skies.' },
  { id: 'molekin', name: 'Molekin', mods: { stone: 1.22, coal: 1.22, aether: 0.85 },
    desc: 'Mole tunnel crews establish deep workshops wherever they settle, following stone and fuel underground.' },
  { id: 'raccoonfolk', name: 'Raccoonfolk', mods: { tools: 1.22, machinery: 1.18, food: 0.90 },
    desc: 'Raccoon salvagers thrive wherever there is work, turning discarded parts into ingenious machines.' },
].map(l => ({ ...l, effect: Object.entries(l.mods).map(([res, mod]) => {
  const pct = Math.round((mod - 1) * 100);
  return `${pct > 0 ? '+' : '−'}${Math.abs(pct)}% ${RESOURCES.find(r => r.id === res).name}`;
}).join(', ') }));

// --- neighboring tribes ---
// Humans are the default people of Emberhold. After each migration, there is
// a chance that a different tribe is encountered as a trading partner.
const TRIBES = [
  { id: 'human', name: 'Human caravans', text: 'Familiar traders follow the old roads.' },
  { id: 'stonekin', name: 'Stonekin', text: 'The Stonekin arrive with mineral goods and careful ledgers.' },
  { id: 'marshfolk', name: 'Marshfolk', text: 'The Marshfolk pole their cargo through the reeds.' },
  { id: 'skyborn', name: 'Skyborn', text: 'The Skyborn descend from the high passes with bright metal.' },
  { id: 'mephit', name: 'Mephit enclaves', text: 'The Mephits arrive in masks and sealed wagons. Their customs are pungent, but their walls are formidable.' },
  { id: 'dunewalkers', name: 'Dunewalker caravans', requests: ['food', 'wood'], loot: ['currency', 'copper', 'tools'],
    text: 'Under indigo awnings, desert merchants weigh every promise. Their caravans seek food and timber to carry between distant markets.' },
  { id: 'cinderforged', name: 'Cinderforged clans', requests: ['wood', 'coal'], loot: ['iron', 'coal', 'steel'],
    text: 'Hammer songs ring from soot-dark wagons. These volcanic smiths prize fuel above finery and settle agreements beside the furnace.' },
  { id: 'thornkin', name: 'Thornkin groves', requests: ['stone', 'tools'], loot: ['food', 'wood', 'tools'],
    text: 'Their homes are woven from living branches. Thornkin trade orchard harvests for stone and tools, but distrust the smoke of heavy industry.' },
  { id: 'clocklings', name: 'Clockling workshops', requests: ['copper', 'iron', 'stone'], loot: ['tools', 'machinery', 'copper'],
    text: 'Tiny brass bells announce each meticulously timed visit. These tireless inventors collect metal and stone for machines that almost never explode.' },
  { id: 'glimmerfolk', name: 'Glimmerfolk choirs', requests: ['food', 'tools'], loot: ['aether', 'knowledge', 'copper'],
    text: 'Lantern-lit travelers sing to crystals until they answer. They exchange fragments of star lore for the provisions their secluded observatories cannot make.' },
  ...ANIMAL_LINEAGES.map(l => ({ id: l.id, name: l.name, text: l.desc, habitats: l.habitats,
    requests: Object.keys(l.mods).filter(r => l.mods[r] < 1),
    loot: Object.keys(l.mods).filter(r => l.mods[r] > 1) })),
];

// --- lineages ---
// A founding choice inspired by Evolve's species specialization, but kept
// complements Emberhold's landing and Echo systems.
const LINEAGES = [
  { id: 'human', name: 'Emberborn', effect: '+20% Industrial Goods production', mods: { goods: 1.20 },
    desc: 'Adaptable survivors who make something useful from almost anything — especially in a factory.' },
  { id: 'stonekin', name: 'Stonekin', effect: '+18% stone and iron, −8% food', mods: { stone: 1.18, iron: 1.18, food: 0.92 },
    desc: 'Broad-shouldered miners who remember the shape of every seam.' },
  { id: 'marshfolk', name: 'Marshfolk', effect: '+18% food and wood, −8% stone', mods: { food: 1.18, wood: 1.18, stone: 0.92 },
    desc: 'Patient growers who turn wet ground and tangled roots into abundance.' },
  { id: 'skyborn', name: 'Skyborn', effect: '+22% knowledge and aether, −10% food', mods: { knowledge: 1.22, aether: 1.22, food: 0.90 },
    desc: 'Clear-eyed wanderers whose maps begin where the clouds end.' },
  { id: 'mephit', name: 'Mephit', effect: '+35% raid defense; raids arrive 120 seconds slower; attackers suffer more injuries', mods: {},
    desc: 'Their settlements stink of sulfur and strange alchemy. Invaders learn to respect the smell.' },
  { id: 'dunewalkers', name: 'Dunewalkers', effect: '+30% currency and +15% copper, −12% wood', mods: { currency: 1.30, copper: 1.15, wood: 0.88 },
    desc: 'A settlement of bustling markets and shaded courtyards. Trade pays for expansion, but scarce timber demands careful planning.' },
  { id: 'cinderforged', name: 'Cinderforged', effect: '+20% iron, coal, and steel, −12% knowledge', mods: { iron: 1.20, coal: 1.20, steel: 1.20, knowledge: 0.88 },
    desc: 'Furnaces are the heart of every home. Rich metalworking supports an industrial rush, while scholars struggle to be heard over the hammers.' },
  { id: 'thornkin', name: 'Thornkin', effect: '+25% wood and +15% food, −15% steel and Industrial Goods', mods: { wood: 1.25, food: 1.15, steel: 0.85, goods: 0.85 },
    desc: 'Living villages spread beneath a generous canopy. Fast early growth comes naturally; bringing heavy industry into the grove takes patience.' },
  { id: 'clocklings', name: 'Clocklings', effect: '+20% tools and +25% machinery, −12% food', mods: { tools: 1.20, machinery: 1.25, food: 0.88 },
    desc: 'Every workshop is an experiment and every tool a prototype. Precision manufacturing flourishes, provided someone remembers to tend the fields.' },
  { id: 'glimmerfolk', name: 'Glimmerfolk', effect: '+30% aether and +15% knowledge, −15% stone and iron', mods: { aether: 1.30, knowledge: 1.15, stone: 0.85, iron: 0.85 },
    desc: 'Crystal gardens illuminate nights spent charting the heavens. Discovery leads the way, but the weight of ordinary construction slows their ascent.' },
  ...ANIMAL_LINEAGES,
];

// --- migration (loop) rewards: Echoes, spent in the ancestral shop.
// Earned on declaring a migration: floor((pop - 10)^2 / 100).
const UPGRADES = [
  { id: 'deepRoots', name: 'Deep Roots', max: 5, costs: [2, 4, 8, 16, 32],
    effect: '+5% to all production, per level',
    desc: 'the village remembers how to flourish' },
  { id: 'wanderers', name: 'Wandering Kin', max: 5, costs: [1, 2, 4, 8, 16],
    effect: '+2 starting villagers and +2 population cap, per level',
    desc: 'kin hear the call and arrive' },
  { id: 'grandHut', name: 'Grand Designs', max: 3, costs: [3, 7, 15],
    effect: 'every Hut grants +1 population cap, per level',
    desc: 'born knowing how to build roomier' },
  { id: 'deepCellars', name: 'Deep Cellars', max: 3, costs: [4, 9, 18],
    effect: 'all storage ceilings +15%, per level',
    desc: 'the knack of keeping is never quite lost' },
  { id: 'lorekeepers', name: 'Lorekeepers', max: 1, costs: [5],
    effect: 'begin each age with a Library raised and 30 Knowledge',
    desc: 'someone always saves the books' },
  { id: 'caravans', name: 'Pack Caravans', max: 1, costs: [8],
    effect: 'begin each age with 300 food, 300 wood, 150 stone, 25 tools',
    desc: 'the wagons are loaded before the leaving' },
  { id: 'oathkeepers', name: 'Oathkeepers', max: 1, costs: [10],
    effect: 'repeatable Trials may be sworn one extra time each',
    desc: 'some oaths outlive the village that swore them' },
  { id: 'oldMaps', name: 'Old Maps', max: 1, costs: [12],
    effect: 'all expedition costs reduced 25%',
    desc: 'the scouts no longer wander lost' },
  { id: 'buildingQueue', name: 'Master Builders', max: 1, costs: [8],
    effect: '+1 construction queue slot',
    desc: 'more hands can raise foundations at once' },
  { id: 'researchQueue', name: 'Grand Archive', max: 1, costs: [8],
    effect: '+1 research queue slot',
    desc: 'more minds can pursue old questions at once' },
];

// --- expeditions: one-time, expand the playing field permanently ---
const EXPEDITIONS = [
  { id: 'emberRoads', name: 'The First Roads', landing: 'emberplain', reqPop: 18,
    cost: { food: 500, stone: 300, tools: 20 }, mods: { food: 1.10 },
    effect: '+10% food production forever',
    text: 'Restore the ash-grass roads and connect the scattered farms of the Emberplain.' },
  { id: 'greenfoldGrove', name: 'The Heartwood Grove', landing: 'greenfold', reqPop: 18,
    cost: { wood: 600, tools: 30 }, mods: { wood: 1.10 },
    effect: '+10% wood production forever',
    text: 'Equip a woodland settlement to chart the oldest groves and learn their patient renewal.' },
  { id: 'grayrocksQuarries', name: 'The High Quarries', landing: 'grayrocks', reqPop: 18,
    cost: { stone: 600, iron: 100, tools: 20 }, mods: { stone: 1.10, iron: 1.05 },
    effect: '+10% stone and +5% iron production forever',
    text: 'Cut a safe route through the Grayrocks and bring the high seams within reach.' },
  { id: 'floodmeadowsChannels', name: 'The Living Channels', landing: 'floodmeadows', reqPop: 18,
    cost: { food: 700, wood: 250, tools: 20 }, mods: { food: 1.10 },
    effect: '+10% food production forever',
    text: 'Follow the floodwaters and establish channels that carry fertile silt to new fields.' },
  { id: 'ashfenFires', name: 'The Sleeping Fires', landing: 'ashfen', reqPop: 18,
    cost: { coal: 400, stone: 300, tools: 25 }, mods: { coal: 1.10 },
    effect: '+10% coal production forever',
    text: 'Provision a marsh camp and map the warm peat beds beneath the smoking ground.' },
  { id: 'windmereSky', name: 'The Mirrored Sky', landing: 'windmere', reqPop: 18,
    cost: { knowledge: 700, wood: 250, tools: 25 }, mods: { knowledge: 1.10, aether: 1.05 },
    effect: '+10% knowledge and +5% aether production forever',
    text: 'Build a lakeside survey camp to record the stars reflected in the still water.' },

  { id: 'oldForest', name: 'The Old Forest', reqPop: 12,
    cost: { wood: 400, tools: 10 },
    effect: '+1.5 wood/s gathered passively, +15% wood production',
    text: 'Beyond the fields stands forest no axe has named. Scouts return with timber like ironwood and stories of wolves.' },

  { id: 'foothills', name: 'The Foothills', reqPop: 15,
    cost: { wood: 350, stone: 550 },
    effect: '+1 stone/s quarried passively, +15% stone production',
    text: 'Where the land lifts, stone lies close to the surface, waiting.' },

  { id: 'sunkenRuins', name: 'The Sunken Ruins', reqPop: 20,
    cost: { knowledge: 1200, tools: 80 },
    effect: '+0.3 knowledge/s, +15% knowledge production, and the lens needed for the Observatory',
    text: 'Half-drowned towers of people who came before. Their libraries are silted but not silent.' },

  { id: 'emberVein', name: 'The Ember Vein', reqPop: 25,
    cost: { steel: 160, coal: 320 },
    effect: '+0.5 coal/s gathered passively, +10% iron production',
    text: 'A seam of coal that burns on its own in the winter. The mountain is warm to the touch.' },

  { id: 'glacialPeaks', name: 'The Glacial Peaks', reqPop: 35,
    cost: { machinery: 90, aether: 30 },
    effect: '+0.1 aether/s gathered passively, +10% to all production',
    text: 'Above the cloud line the air is thin and clear, and the stars seem close enough to harvest.' },
];

// --- season food multipliers ---
const SEASONS = [
  { name: 'Spring', mult: 1.0 },
  { name: 'Summer', mult: 1.05 },
  { name: 'Autumn', mult: 0.9 },
  { name: 'Winter', mult: 0.5 }, // 0.75 with Everwarm, 0.25 during Long Night
];
